In [16]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [17]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import numpy as np
from scipy.sparse import lil_matrix


import nmrtools

In [18]:
def spin8():
    v = np.array([85, 120, 160, 185, 205, 215, 235, 260])
    # Note: previous version used a scipy lil_matrix for J, but hamiltonian
    # gave a dimension mismatch. Changed to a np matrix and worked.
    J = np.zeros((8, 8))
    J[0, 1] = -12
    J[0, 2] = 6
    J[0, 3] = 2
    # J[0, 4] = 0
    # J[0, 5] = 0
    # J[0, 6] = 0
    # J[0, 7] = 0
    # J[1, 2] = 0
    # J[1, 3] = 0
    J[1, 4] = 14
    # J[1, 5] = 0
    # J[1, 6] = 0
    J[1, 7] = 3
    # J[2, 3] = 0
    # J[2, 4] = 0
    J[2, 5] = 3
    # J[2, 6] = 0
    # J[2, 7] = 0
    # J[3, 4] = 0
    J[3, 5] = 5
    # J[3, 6] = 0
    # J[3, 7] = 0
    J[4, 5] = 2
    # J[4, 6] = 0
    # J[4, 7] = 0
    # J[5, 6] = 0
    # J[5, 7] = 0
    J[6, 7] = 12
    J = J + J.T
    return v, J

In [19]:
v, J = spin8()
print(v)
print(J)

[ 85 120 160 185 205 215 235 260]
[[  0. -12.   6.   2.   0.   0.   0.   0.]
 [-12.   0.   0.   0.  14.   0.   0.   3.]
 [  6.   0.   0.   0.   0.   3.   0.   0.]
 [  2.   0.   0.   0.   0.   5.   0.   0.]
 [  0.  14.   0.   0.   0.   2.   0.   0.]
 [  0.   0.   3.   5.   2.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  12.]
 [  0.   3.   0.   0.   0.   0.  12.   0.]]


In [20]:
H = nmrtools.nmrmath.hamiltonian(v, J)
H

matrix([[ 741.25,    0.  ,    0.  , ...,    0.  ,    0.  ,    0.  ],
        [   0.  ,  473.75,    6.  , ...,    0.  ,    0.  ,    0.  ],
        [   0.  ,    6.  ,  500.25, ...,    0.  ,    0.  ,    0.  ],
        ...,
        [   0.  ,    0.  ,    0.  , ..., -494.75,    6.  ,    0.  ],
        [   0.  ,    0.  ,    0.  , ...,    6.  , -471.25,    0.  ],
        [   0.  ,    0.  ,    0.  , ...,    0.  ,    0.  , -723.75]])

In [21]:
help(nmrtools.nmrmath)

Help on module nmrtools.nmrmath in nmrtools:

NAME
    nmrtools.nmrmath - Provides functions for the calculation of NMR spectra.

DESCRIPTION
    This version of nmrmath features speed-optimized hamiltonian, simsignals,
    and transition_matrix functions. Up to at least 8 spins, the new non-sparse
    Hamilton code is about 10x faster. The overall performance is dramatically
    better than the original code.
    
    TODO: elaborate; list functions; provide examples.
    
    References
    ----------
    
    Formulas for simulating two uncoupled spin-1/2 nuclei are derived from:
    Sandstrom, J. *Dynamic NMR Spectroscopy*; Academic Press, 1982, p. 15.
    
    Formulas for simulating two coupled spin-1/2 nuclei are derived from:
    Brown, K.C.; Tyson, R. L.; Weil, J. A. *J. Chem. Educ.* **1998**, *75*, 1632.
    (NOTE: Hans Reich pointed out that the paper has a sign typo in Equation (2b)!
    the last term is minus-over-plus, not plus-over-minus.)

CLASSES
    builtins.object
  

In [22]:
import pickle

In [23]:
with open('hamiltonian.pickle', 'wb') as f:
    # Pickle the 'data' dictionary using the highest protocol available.
    pickle.dump(H, f, pickle.HIGHEST_PROTOCOL)

In [24]:
with open('hamiltonian.pickle', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    new_H = pickle.load(f)
new_H

matrix([[ 741.25,    0.  ,    0.  , ...,    0.  ,    0.  ,    0.  ],
        [   0.  ,  473.75,    6.  , ...,    0.  ,    0.  ,    0.  ],
        [   0.  ,    6.  ,  500.25, ...,    0.  ,    0.  ,    0.  ],
        ...,
        [   0.  ,    0.  ,    0.  , ..., -494.75,    6.  ,    0.  ],
        [   0.  ,    0.  ,    0.  , ...,    6.  , -471.25,    0.  ],
        [   0.  ,    0.  ,    0.  , ...,    0.  ,    0.  , -723.75]])

In [25]:
s = f'h{len(v)}'
s

'h8'